### ISSUE TITLE
No matching distribution found for dataclasses==0.8

### ISSUE THREAD

**Issue by momo-the-monster** [cansik/mediapipe-osc#2]
pip install of requirements.txt failed with this error above on Windows 10 64-Bit with Python 3.9.4

**Comment by momo-the-monster** [comment]
It looks like this import [may not be necessary](https://pypi.org/project/dataclasses/) for Python versions greater than 3.7?
Also worth noting that mediapipe 0.8.2 seems to no longer be available, and mediapipe 0.8.3 requires numpy 1.19.3.

**Comment by cansik** [comment]
Thanks for pointing this out, I fixed it in the most recent commit.
